language: python
python:
    - "2.7"
    - "3.6"

notifications:
  email: change

sudo: false

cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run

